
title: FADHILLA ELITA # your title
url: 'http://tata13.github.io'
baseurl: '/tata13.github.io' #change it according to your repository name



# Profile information
yourname: FADHILLA ELITA  ## put your name
location: Pekanbaru, Indonesia


## Social Profiles
facebook: https://www.facebook.com/thata.lamonade?ref=bookmarks  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/fadhilla-elita-4542b6134/## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url
instagram: https://www.instagram.com/tata131295/?hl=id



# Update all the sections by editing the files inside _includes folder.
